### PR TITLE
[ADD] OCA modules

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
Related: https://github.com/qrtl/sst-custom/pull/318

### CODE REVIEW

**Comment by yostashiro** [comment]
@AungKoKoLin1997 Do you know what's causing such a large diff?
image

**Comment by AungKoKoLin1997** [comment]
>Do you know what's causing such a large diff?

@yostashiro After I checked, I found web_responsive/lib is missing because of [gitignore](https://github.com/qrtl/sst-oca/blob/a3255a0b6ee37434e26528af19eed8ff86533120/.gitignore#L17). Sorry, I didn't expect that and didn't check .gitignore. I will create PR to update `.gitignore` and also update this PR.

**Comment by AungKoKoLin1997** [comment]
I didn't add setup file to be clear for checking files count. I will generate setup folder after approved.

**Review by yostashiro — APPROVED** [review]
Thanks Lin!

**Review by kanda999 — APPROVED** [review]
Function review.

**Pull request merged**
